import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SiteHeader } from '../src/components/SiteHeader';
import { colors, spacing } from '../src/theme';

export default function AboutScreen() { const router = useRouter(); return <View style={styles.screen}><SiteHeader /><ScrollView contentContainerStyle={styles.content}><Image source={require('../assets/images/logo.png')} style={styles.logo} resizeMode="contain" /><Text style={styles.eyebrow}>SOBRE A STICK ADESIVOS</Text><Text style={styles.title}>Personalização simples para quem cuida da própria marca.</Text><Text style={styles.lead}>A Stick Adesivos reúne formatos, materiais e acabamentos para marcas, embalagens e produtos. O app foi organizado para tornar a escolha clara desde o primeiro contato até o envio da arte.</Text><View style={styles.story}><Text style={styles.storyTitle}>Do seu arquivo ao pedido</Text><Text style={styles.storyText}>Você escolhe o produto, define tamanho e quantidade e envia a arte no momento mais conveniente. Cada etapa mostra apenas as informações necessárias para seguir com segurança.</Text><Pressable onPress={() => router.push({ pathname: '/produto/[slug]', params: { slug: 'adesivo-redondo-personalizado' } })}><Text style={styles.link}>Veja como personalizar <Text>→</Text></Text></Pressable></View><View style={styles.principles}><Principle n="01" title="Escolha clara" text="Produtos organizados por formato, material e uso." /><Principle n="02" title="Processo direto" text="Configuração, envio de arte e carrinho sem etapas desnecessárias." /><Principle n="03" title="Atendimento próximo" text="Um canal para tirar dúvidas antes de concluir o pedido." /></View><View style={styles.cta}><Text style={styles.ctaTitle}>Encontre o adesivo ideal para sua marca.</Text><Text style={styles.ctaText}>Compare as opções disponíveis ou comece por um modelo personalizado.</Text><Pressable style={styles.primary} onPress={() => router.push('/(tabs)/catalogo')}><Text style={styles.primaryText}>Ver produtos</Text><Ionicons name="arrow-forward" size={16} color={colors.white} /></Pressable></View></ScrollView></View>; }
function Principle({ n, title, text }: { n: string; title: string; text: string }) { return <View style={styles.principle}><Text style={styles.number}>{n}</Text><View style={{ flex: 1 }}><Text style={styles.principleTitle}>{title}</Text><Text style={styles.principleText}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.white }, content: { padding: spacing.md, paddingBottom: 40 }, logo: { width: 145, height: 78, alignSelf: 'center', marginBottom: 14 }, eyebrow: { textAlign: 'center', color: colors.blue, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.ink, textAlign: 'center', fontSize: 27, lineHeight: 33, fontWeight: '900', marginTop: 9 }, lead: { color: colors.text, textAlign: 'center', fontSize: 14, lineHeight: 21, marginTop: 13 }, story: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 22, marginTop: 25 }, storyTitle: { color: colors.ink, fontSize: 20, fontWeight: '900' }, storyText: { color: colors.text, fontSize: 14, lineHeight: 21, marginTop: 8 }, link: { color: colors.blue, fontSize: 13, fontWeight: '800', marginTop: 13 }, principles: { marginTop: 23, gap: 14 }, principle: { flexDirection: 'row', gap: 13, alignItems: 'flex-start' }, number: { color: colors.blue, fontSize: 18, fontWeight: '900' }, principleTitle: { color: colors.ink, fontWeight: '900', fontSize: 14 }, principleText: { color: colors.text, fontSize: 12, lineHeight: 18, marginTop: 3 }, cta: { marginTop: 25, padding: spacing.md, borderRadius: 10, backgroundColor: colors.blueSoft }, ctaTitle: { color: colors.ink, fontSize: 19, lineHeight: 24, fontWeight: '900' }, ctaText: { color: colors.text, fontSize: 13, lineHeight: 18, marginTop: 6 }, primary: { backgroundColor: colors.blue, minHeight: 43, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, borderRadius: 6, marginTop: 14 }, primaryText: { color: colors.white, textTransform: 'uppercase', fontWeight: '800', fontSize: 12 }
});
