import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SiteHeader } from '../../src/components/SiteHeader';
import { colors, spacing } from '../../src/theme';

export default function ContactScreen() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState('');
  const send = () => { if (!name.trim() || !email.trim() || !message.trim()) { Alert.alert('Preencha os campos', 'Nome, e-mail e mensagem são obrigatórios.'); return; } Alert.alert('Mensagem preparada', 'O canal oficial de atendimento será conectado nesta etapa.'); };
  return <View style={styles.screen}><SiteHeader /><ScrollView contentContainerStyle={styles.content}><View style={styles.intro}><Text style={styles.eyebrow}>CONTATO</Text><Text style={styles.title}>Como podemos <Text style={styles.pink}>ajudar?</Text></Text><Text style={styles.lead}>Envie sua dúvida sobre produtos, personalização ou um pedido em andamento.</Text><View style={styles.note}><Ionicons name="information-circle-outline" size={20} color={colors.blue} /><Text style={styles.noteText}>Inclua o produto desejado e, se já tiver um pedido, informe a referência.</Text></View></View><View style={styles.form}><Field label="Nome *" value={name} onChangeText={setName} placeholder="Seu nome" /><Field label="E-mail *" value={email} onChangeText={setEmail} placeholder="seu@email.com" keyboardType="email-address" /><Field label="WhatsApp" placeholder="(00) 00000-0000" /><Field label="Assunto *" placeholder="Como podemos ajudar?" /><Text style={styles.label}>Mensagem *</Text><TextInput value={message} onChangeText={setMessage} placeholder="Escreva sua mensagem" placeholderTextColor={colors.muted} multiline numberOfLines={5} textAlignVertical="top" style={[styles.input, styles.textarea]} /><Pressable style={styles.primary} onPress={send}><Text style={styles.primaryText}>Enviar mensagem</Text></Pressable></View></ScrollView></View>;
}

function Field({ label, value, onChangeText, placeholder, keyboardType }: { label: string; value?: string; onChangeText?: (value: string) => void; placeholder: string; keyboardType?: 'default' | 'email-address' }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType} style={styles.input} /></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.white }, content: { padding: spacing.md, paddingBottom: 35 }, intro: { paddingTop: 9 }, eyebrow: { color: colors.blue, fontSize: 11, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.ink, fontSize: 29, lineHeight: 35, fontWeight: '900', marginTop: 8 }, pink: { color: colors.pink }, lead: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 11 }, note: { marginTop: 18, backgroundColor: colors.blueSoft, borderRadius: 8, padding: 12, flexDirection: 'row', gap: 9 }, noteText: { flex: 1, color: colors.text, fontSize: 12, lineHeight: 18 }, form: { marginTop: 22, padding: spacing.md, borderWidth: 1, borderColor: colors.line, borderRadius: 10 }, field: { marginBottom: 14 }, label: { color: colors.ink, fontSize: 12, fontWeight: '800', marginBottom: 6 }, input: { height: 44, borderWidth: 1, borderColor: colors.line, borderRadius: 6, paddingHorizontal: 11, color: colors.ink, fontSize: 13 }, textarea: { height: 125, paddingTop: 11 }, primary: { minHeight: 45, borderRadius: 6, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center', marginTop: 16 }, primaryText: { color: colors.white, textTransform: 'uppercase', fontWeight: '800', fontSize: 12 }
});
