import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Image, ImageBackground, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ProductCard } from '../../src/components/ProductCard';
import { SectionTitle } from '../../src/components/SectionTitle';
import { useProductCatalog } from '../../src/context/ProductCatalogContext';
import { colors, spacing } from '../../src/theme';
import { SiteHeader } from '../../src/components/SiteHeader';

export default function HomeScreen() {
  const router = useRouter();
  const { products } = useProductCatalog();
  return <View style={styles.screen}><SiteHeader /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <ImageBackground source={require('../../assets/images/hero-banner.png')} resizeMode="cover" style={styles.hero} imageStyle={styles.heroImage}>
      <View style={styles.heroCopy}><Text style={styles.heroTitle}>Adesivos personalizados para <Text style={styles.blue}>destacar</Text> sua <Text style={styles.pink}>marca.</Text></Text><Text style={styles.heroText}>Impressão de alta definição, materiais premium e acabamento impecável para o seu negócio.</Text><View style={styles.heroButtons}><Pressable style={styles.primaryButton} onPress={() => router.push({ pathname: '/produto/[slug]', params: { slug: products[0].slug } })}><Text style={styles.primaryText}>Criar meu adesivo</Text><Ionicons name="arrow-forward" size={16} color={colors.white} /></Pressable><Pressable style={styles.outlineButton} onPress={() => router.push('/(tabs)/catalogo')}><Text style={styles.outlineText}>Ver catálogo</Text></Pressable></View></View>
    </ImageBackground>

    <View style={styles.benefits}><Benefit icon="shield-checkmark-outline" title="Materiais premium" text="Mais resistência e durabilidade." /><Benefit icon="scan-outline" title="Alta definição" text="Cores vivas e detalhes incríveis." /><Benefit icon="headset-outline" title="Atendimento especializado" text="Do pedido à entrega, com você." /></View>

    <View style={styles.section}><SectionTitle action="Ver todos">Mais <Text style={styles.pink}>vendidos</Text></SectionTitle><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontalProducts}>{products.slice(0, 4).map((product) => <View key={product.id} style={styles.horizontalCard}><ProductCard product={product} /></View>)}</ScrollView></View>

    <ImageBackground source={require('../../assets/images/hero-products.png')} resizeMode="cover" style={styles.promo} imageStyle={styles.promoImage}><View style={styles.promoShade}><Text style={styles.promoTitle}>Sua marca. <Text style={styles.pink}>Do seu jeito.</Text></Text><Text style={styles.promoText}>Personalize seus adesivos com o formato, tamanho e acabamento que combinam com a identidade da sua marca.</Text><Pressable style={styles.promoButton} onPress={() => router.push({ pathname: '/produto/[slug]', params: { slug: products[0].slug } })}><Text style={styles.primaryText}>Criar meu adesivo</Text><Ionicons name="arrow-forward" size={16} color={colors.white} /></Pressable></View></ImageBackground>

    <View style={styles.section}><SectionTitle action="Ver todos">Destaques <Text style={styles.pink}>personalizados</Text></SectionTitle><View style={styles.grid}>{products.slice(4, 8).map((product) => <View key={product.id} style={styles.gridItem}><ProductCard product={product} /></View>)}</View></View>

    <View style={styles.how}><SectionTitle>Como <Text style={styles.pink}>funciona</Text></SectionTitle><View style={styles.steps}><Step number="1" title="Escolha" text="Encontre o modelo, formato e acabamento ideal." /><Step number="2" title="Envie sua arte" text="Mande o arquivo ou as informações do seu projeto." /><Step number="3" title="Produzimos" text="Cuidamos da impressão com atenção aos detalhes." /><Step number="4" title="Receba" text="Seu pedido chega pronto para usar." /></View></View>
  </ScrollView></View>;
}

function Benefit({ icon, title, text }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string }) { return <View style={styles.benefit}><Ionicons name={icon} size={25} color={colors.ink} /><View style={styles.benefitCopy}><Text style={styles.benefitTitle}>{title}</Text><Text style={styles.benefitText}>{text}</Text></View></View>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <View style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{number}</Text></View><View style={{ flex: 1 }}><Text style={styles.stepTitle}>{title}</Text><Text style={styles.stepText}>{text}</Text></View></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.white }, content: { paddingBottom: 34 }, hero: { minHeight: 340, justifyContent: 'center', paddingHorizontal: spacing.lg, overflow: 'hidden' }, heroImage: { opacity: 0.24 }, heroCopy: { maxWidth: 420 }, heroTitle: { fontSize: 29, lineHeight: 34, fontWeight: '900', color: colors.ink }, blue: { color: colors.blue }, pink: { color: colors.pink }, heroText: { marginTop: 12, color: colors.text, fontSize: 15, lineHeight: 21, maxWidth: 285 }, heroButtons: { flexDirection: 'row', gap: 10, marginTop: 20, flexWrap: 'wrap' }, primaryButton: { minHeight: 44, paddingHorizontal: 15, borderRadius: 6, backgroundColor: colors.blue, flexDirection: 'row', alignItems: 'center', gap: 8 }, primaryText: { color: colors.white, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' }, outlineButton: { minHeight: 44, paddingHorizontal: 17, borderRadius: 6, borderWidth: 1.5, borderColor: colors.pink, alignItems: 'center', justifyContent: 'center' }, outlineText: { color: colors.ink, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' }, benefits: { borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, padding: spacing.md, gap: 14 }, benefit: { flexDirection: 'row', alignItems: 'center', gap: 12 }, benefitCopy: { flex: 1 }, benefitTitle: { fontSize: 13, color: colors.ink, fontWeight: '800' }, benefitText: { color: colors.text, fontSize: 11, marginTop: 2 }, section: { padding: spacing.md, paddingTop: 26 }, horizontalProducts: { gap: 12, paddingBottom: 4 }, horizontalCard: { width: 260 }, promo: { marginHorizontal: spacing.md, minHeight: 170, borderRadius: 10, overflow: 'hidden', backgroundColor: '#101317' }, promoImage: { opacity: 0.35 }, promoShade: { padding: spacing.lg, justifyContent: 'center', flex: 1 }, promoTitle: { color: colors.white, fontSize: 23, fontWeight: '900' }, promoText: { color: '#E8EBF0', fontSize: 12, lineHeight: 17, maxWidth: 245, marginTop: 7 }, promoButton: { alignSelf: 'flex-start', marginTop: 15, minHeight: 38, paddingHorizontal: 13, borderRadius: 6, backgroundColor: colors.blue, flexDirection: 'row', alignItems: 'center', gap: 7 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, gridItem: { width: '48.2%' }, how: { padding: spacing.md, paddingTop: 12 }, steps: { gap: 14 }, step: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, stepNumber: { width: 29, height: 29, borderRadius: 15, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, stepNumberText: { color: colors.white, fontWeight: '900' }, stepTitle: { fontWeight: '800', color: colors.ink, fontSize: 14 }, stepText: { color: colors.text, fontSize: 12, marginTop: 2, lineHeight: 17 }
});
